development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vino_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: vino_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: 10.0.2.12
  port: 26481
  database: demo_db
  pool: 5
  username: cpegwlfjp098tpm4
  password: ani8ziy1oo7w1bwjcgnqct9qzhwg0dx
